baseURL = "https://jbszczepaniak.github.io/gott/"
languageCode = "en-us"
title = "Go on the toilet"
theme = "ananke"
pygmentsStyle = "native"
background_color_class = "bg-blue"
publishDir = "docs"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jbszczepaniak/gott"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 100
